In [5]:
import pandas as pd 
import numpy as np

In [6]:
df = pd.read_csv('mnist_train.csv')

In [7]:
df.head()

label  1x1  1x2  1x3  1x4  1x5  1x6  1x7  1x8  1x9  ...  28x19  28x20  \
0      5    0    0    0    0    0    0    0    0    0  ...      0      0   
1      0    0    0    0    0    0    0    0    0    0  ...      0      0   
2      4    0    0    0    0    0    0    0    0    0  ...      0      0   
3      1    0    0    0    0    0    0    0    0    0  ...      0      0   
4      9    0    0    0    0    0    0    0    0    0  ...      0      0   

   28x21  28x22  28x23  28x24  28x25  28x26  28x27  28x28  
0      0      0      0      0      0      0      0      0  
1      0      0      0      0      0      0      0      0  
2      0      0      0      0      0      0      0      0  
3      0      0      0      0      0      0      0      0  
4      0      0      0      0      0      0      0      0  

[5 rows x 785 columns]

In [8]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df.iloc[:,1:],df.iloc[:,0],test_size=0.2,random_state=2)

In [9]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier

In [10]:
clf1 = LogisticRegression()
clf2 = DecisionTreeClassifier()

In [11]:
clf1.fit(X_train,y_train)
clf2.fit(X_train,y_train)

c:\Users\rosha\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


DecisionTreeClassifier()

In [12]:
y_pred1 = clf1.predict(X_test)
y_pred2 = clf2.predict(X_test)

In [13]:
from sklearn.metrics import accuracy_score,confusion_matrix
print("Accuracy of Logistic Regression",accuracy_score(y_test,y_pred1))
print("Accuracy of Decision Trees",accuracy_score(y_test,y_pred2))

Accuracy of Logistic Regression 0.9171666666666667
Accuracy of Decision Trees 0.8695


In [14]:
print("Logistic Regression Confusion Matrix\n")
pd.DataFrame(confusion_matrix(y_test,y_pred1),columns=list(range(0,10)))

Logistic Regression Confusion Matrix



0     1     2     3     4    5     6     7     8     9
0  1139     0     6     3     1   11    10     4     9     0
1     0  1306     8     3     6   10     2     5    12     2
2     8    14  1066    27    11    5    19    13    25     6
3     3     6    27  1126     2   34     3    10    29    12
4     3     4    12     2  1133    2    11     6     8    36
5    16    10    11    32     9  931    21     7    39     7
6     6     5    11     1    12   18  1110     1     5     0
7     4     3    14    10    12    2     0  1128     5    42
8     3    27    11    31     8   32     7     7  1031     9
9     3     2     4    15    43   10     0    32    17  1036

In [15]:
print("Decision Tree Confusion Matrix\n")
pd.DataFrame(confusion_matrix(y_test,y_pred2),columns=list(range(0,10)))

Decision Tree Confusion Matrix



0     1     2     3     4    5     6     7    8    9
0  1067     3    17    10    11   23    22     5   17    8
1     0  1289    15     9     6    9    11     4    7    4
2    15    13  1014    28    13   12    28    25   30   16
3     6    12    41  1064     8   49     4     7   36   25
4     7     7    16     8  1068   14    18    10   22   47
5    17    17     7    56    10  875    35    11   33   22
6    18     7    19     8    20   25  1047     4   14    7
7     5     6    21    15    22    6     1  1109   13   22
8     9    20    28    37    26   33    21    12  941   39
9     7     9    15    21    54   20     3    34   39  960

In [16]:
from sklearn.metrics import precision_score,recall_score,f1_score


In [ ]:
precision_score(y_test,y_pred1,average=None)  # har class ka precission alag se calcualted hokar dikhiye dega 

array([0.96118143, 0.94843863, 0.91111111, 0.9008    , 0.91592563,
       0.88246445, 0.93829248, 0.9299258 , 0.87372881, 0.90086957])

In [17]:
precision_score(y_test,y_pred1,average='weighted')

0.917022827062738

In [26]:
precision_score(y_test,y_pred1,average='macro')


0.916273792123846

In [23]:
recall_score(y_test,y_pred1,average=None)  # har class ka precission alag se calcualted hokar dikhiye dega 

array([0.96280642, 0.96454948, 0.89279732, 0.89936102, 0.93097781,
       0.85964912, 0.94952951, 0.92459016, 0.88421955, 0.89156627])

In [18]:
recall_score(y_test,y_pred1,average='weighted')

0.9171666666666667

In [24]:
f1_score(y_test,y_pred1,average=None)  # har class ka precission alag se calcualted hokar dikhiye dega 

array([0.96199324, 0.95642622, 0.90186125, 0.90007994, 0.92339038,
       0.87090739, 0.94387755, 0.92725031, 0.87894288, 0.89619377])

In [29]:
f1_score(y_test,y_pred1,average='weighted')

0.9170485929607194

In [20]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred1))

              precision    recall  f1-score   support

           0       0.96      0.96      0.96      1183
           1       0.95      0.96      0.96      1354
           2       0.91      0.89      0.90      1194
           3       0.90      0.90      0.90      1252
           4       0.92      0.93      0.92      1217
           5       0.88      0.86      0.87      1083
           6       0.94      0.95      0.94      1169
           7       0.93      0.92      0.93      1220
           8       0.87      0.88      0.88      1166
           9       0.90      0.89      0.90      1162

    accuracy                           0.92     12000
   macro avg       0.92      0.92      0.92     12000
weighted avg       0.92      0.92      0.92     12000

